# 1주차 과제 공지사항

----

1. 아래의 과제를 보고 답안을 작성하시면 됩니다.
2. 과제에 대한 점수는 100점 만점으로 진행이 됩니다.
3. 과제에 대한 평가는 모든 수강생들의 평가가 완료되면 확인할 수 있습니다. 참고부탁드립니다.
4. 과제기한은 일요일 저녁 10시 까지 입니다. 10시 이후에는 이 불가하오니 이 점 참고부탁드립니다.



----

# 과제1. 행렬 곱

행렬 A와 벡터 b의 곱 Ab을 구하시오.
```
A = [ [1,2,-1],
      [2,7,4],
      [0,4,-1] ]

b = [1,0,1.2]     
```


행렬 A와 행렬 B의 곱 AB을 구하시오.
```
A = [ [1,2,-1],
      [2,7,4],
      [0,4,-1] ]

B = [ [1,2,3,4],
      [-1,2,3,1],
      [3,-2,5,9] ]
```

힌트. numpy.matmul(A,b)

아래에 답안을 작성해 주세요.








array([-0.2,  6.8, -1.2])

array([[-4,  8,  4, -3],
       [ 7, 10, 47, 51],
       [-7, 10,  7, -5]])

# 과제2. Norm

벡트 b의 1차 norm, 2차 norm을 구하시오.
```
b = [1,0,1.2]
```

힌트. scipy.linalg.norm()

아래에 답안을 작성해 주세요.














1차 : 2.2

2차 : 1.5620499351813308

# 과제3. 고유값 분해
행렬 A의 고유값과 고유벡터를 구하시오.
```
A = [ [4,2],
      [3,5] ]
```

힌트. numpy.linalg.eig()

아래에 답안을 작성해 주세요.








고유값
[2. 7.]

고유벡터
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]

#과제4. 유사역행렬
행렬 A의 유사역행렬을 구하시오.
```
A = [ [1,1],
      [0,0],
      [0,0] ]
```

힌트. scipy.linalg.pinv()


아래에 답안을 작성해 주세요.









array([[0.5, 0. , 0. ],
       [0.5, 0. , 0. ]])

# 과제5. 퍼셉트론
벡터 x, 벡터 w, 값 b가 다음과 같은 값을 갖을 때
```
x = [ 1, 2, 3 ]
w = [ -1, 0, 1 ]
b = 1
```

wx의 값, wx + b의 값, relu(wx + b)의 값을 구하시오.

함수 relu(a)는 max(0,a)입니다.

아래에 답안을 작성해 주세요.








3